tests: Flow/Neos version increased to 2.3 and 1.2, respectively
Also this change contain some changes how the tests are running against Flow. We don't need to start separate container with 'T3APP_DO_INIT_TESTS' var set to TRUE as this is only necessary for Behat testing. We can run unit and functional Flow tests without the need to launch separate container.

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -58,31 +58,20 @@ test:
     - curl -L --head http://flow:8000 && curl -s -L http://flow:8000
     - curl -s -L --head http://flow:8000 | grep "HTTP/1.1 200 OK" && curl -s -L --head http://flow:8000 | grep "X-Flow-Powered" && curl -s -L --head http://flow:8000 | grep "/flow/welcome"
     - curl -s -L http://flow:8000 | grep "Kickstart your first package"
-    # Test: check if Flow is installed in $T3APP_NAME directory
-    - docker run -ti --volumes-from=flow million12/php-app "su www -c \"cd && ls -al flow\""
-    # Clean up
-    - docker rm -f flow || true
-    
-    
-    # ###################################################################
-    # Launch Flow container again, but do only initialisation for testing
-    # ###################################################################
-    - docker run -d --name=flow-testing --link=db:db --env="T3APP_DO_INIT=false" --env="T3APP_DO_INIT_TESTS=true" test/typo3-flow
-    - docker logs -f flow-testing > ${CIRCLE_ARTIFACTS}/docker-flow-testing.log:
-        background: true
-    # Run all Flow tests (unit, functional), but do not fail the build in case of any problems there. These are vendor tests and errors there do not indicate that this Docker image is faulty.
-    # Note: we do not need Selenium container here as Flow doesn't have Behat tests. Therefore we use simple PHP container.
+    # Run all Flow tests (unit, functional)
+    # Note: we do not need Selenium container here as Flow doesn't have Behat tests. 
+    # Therefore we use million12/php-app container, which is also the base image for our project.
     - |
-      docker run -ti --volumes-from=flow-testing --link=flow-testing:web --link=db:db million12/php-app "
+      docker run -ti --volumes-from=flow --link=flow:web --link=db:db million12/php-app "
         su www -c \"
-          cd ~/typo3-app && \
-          echo -e '\n\n======== RUNNING TYPO3 FLOW TESTS =======\n\n' && \
-          bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml && \
+          cd ~/flow; \
+          echo -e '\n\n======== RUNNING TYPO3 FLOW TESTS =======\n\n'; \
+          bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml; \
           bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml
         \"
-      " || true
+      "
     # Clean up
-    - docker rm -f flow-testing || true
+    - docker rm -f flow || true
     
     
     # ##################################################
@@ -98,7 +87,7 @@ test:
     # Test: do basic front-end tests 
     - curl -L --head http://neos:8100 && curl -s -L http://neos:8100
     - curl -s --head http://neos:8100 | grep "HTTP/1.1 200 OK" && curl -s --head http://neos:8100 | grep "X-Flow-Powered"
-    - curl -s http://neos:8100 | grep "Planned for change" && curl -s http://neos:8100 | grep "Powered by TYPO3 Neos"
+    - curl -s http://neos:8100 | grep "Power when you need it" && curl -s http://neos:8100 | grep "Powered by TYPO3 Neos"
     - curl -s -L http://neos:8100/neos | grep "TYPO3 Neos Login"
     # Test: check if Neos is installed in $T3APP_NAME directory
     - docker run -ti --volumes-from=neos million12/php-app "su www -c \"cd && ls -al neos\""
@@ -109,27 +98,29 @@ test:
     # ###################################################################
     # Launch Neos container again, but do only initialisation for testing
     # ###################################################################
-    - docker run -d --name=neos-testing -p=8200:80 --link=db:db --env="T3APP_DO_INIT=false" --env="T3APP_DO_INIT_TESTS=true" --env="T3APP_VHOST_NAMES=neos dev.behat.neos" test/typo3-neos
+    - docker run -d --name=neos-testing -p=8200:80 --link=db:db --env="T3APP_DO_INIT_TESTS=true" --env="T3APP_VHOST_NAMES=neos dev.neos behat.dev.neos" test/typo3-neos
     - docker logs -f neos-testing > ${CIRCLE_ARTIFACTS}/docker-neos-testing.log:
         background: true
     # Wait till TYPO3 Neos is fully configured
     - while true; do if grep "nginx entered RUNNING state" -a ${CIRCLE_ARTIFACTS}/docker-neos-testing.log; then break; else sleep 1; fi done
     - curl -L --head http://neos:8200 && curl -s -L http://neos:8200
-    # DB was not configured, so expect 'Database Error' if you go to front-end page
-    - curl -s -L http://neos:8200 | grep "Database Error"    
-    # Run all Neos tests (unit, functional, behat), but do not fail the build in case of any problems there. These are vendor tests and errors there do not indicate that this Docker image is faulty.
+    
+    # Run all Neos tests (unit, functional, behat), but do not fail the build in case of 
+    # any problems there. These are vendor tests and errors there 
+    # do not indicate that this Docker image is faulty.
     - |
       docker run -ti --volumes-from=neos-testing --link=neos-testing:web --link=db:db million12/behat-selenium "
         env && \
         echo \$WEB_PORT_80_TCP_ADDR \$WEB_ENV_T3APP_VHOST_NAMES >> /etc/hosts && cat /etc/hosts && \
         su www -c \"
-          cd ~/typo3-app && \
-          echo -e '\n\n======== RUNNING TYPO3 NEOS TESTS =======\n\n' && \
-          bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml && \
-          bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml && \
+          cd ~/typo3-app; \
+          echo -e '\n\n======== RUNNING TYPO3 NEOS TESTS =======\n\n'; \
+          bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml; \
+          bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml; \
           bin/behat -c Packages/Application/TYPO3.Neos/Tests/Behavior/behat.yml
         \"
       " || true
+    
     # Clean up
     - docker rm -f neos-testing || true
 
